// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BlacklistService 管理供应商黑名单
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoRecoverExpired 自动恢复过期的黑名单（由定时器调用）
 * 使用事务批量处理，避免多次单独写入导致的并发锁冲突
 */
export function AutoRecoverExpired(): $CancellablePromise<void> {
    return $Call.ByID(1788747233);
}

/**
 * GetBlacklistStatus 获取所有黑名单状态（用于前端展示，支持等级拉黑）
 */
export function GetBlacklistStatus(platform: string): $CancellablePromise<$models.BlacklistStatus[]> {
    return $Call.ByID(2289061434, platform).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsBlacklisted 检查 provider 是否在黑名单中
 */
export function IsBlacklisted(platform: string, providerName: string): $CancellablePromise<[boolean, time$0.Time | null]> {
    return $Call.ByID(237122095, platform, providerName);
}

/**
 * IsLevelBlacklistEnabled 返回等级拉黑功能是否开启
 * 用于 proxyHandler 判断是否启用自动降级
 */
export function IsLevelBlacklistEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1770379115);
}

/**
 * ManualResetLevel 手动清零等级（不解除拉黑，仅重置等级）
 */
export function ManualResetLevel(platform: string, providerName: string): $CancellablePromise<void> {
    return $Call.ByID(1066300442, platform, providerName);
}

/**
 * ManualUnblock 手动解除拉黑（向后兼容，调用 ManualUnblockAndReset）
 */
export function ManualUnblock(platform: string, providerName: string): $CancellablePromise<void> {
    return $Call.ByID(3158432043, platform, providerName);
}

/**
 * ManualUnblockAndReset 手动解除拉黑（保留等级，如需清零请调用 ManualResetLevel）
 */
export function ManualUnblockAndReset(platform: string, providerName: string): $CancellablePromise<void> {
    return $Call.ByID(3733422827, platform, providerName);
}

/**
 * RecordFailure 记录 provider 失败，连续失败次数达到阈值时自动拉黑（支持等级拉黑）
 */
export function RecordFailure(platform: string, providerName: string): $CancellablePromise<void> {
    return $Call.ByID(640211172, platform, providerName);
}

/**
 * RecordSuccess 记录 provider 成功，清零连续失败计数，执行降级和宽恕逻辑
 */
export function RecordSuccess(platform: string, providerName: string): $CancellablePromise<void> {
    return $Call.ByID(555083369, platform, providerName);
}

// Private type creation functions
const $$createType0 = $models.BlacklistStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
