// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CliConfigService CLI 配置管理服务
 * 管理 Claude Code、Codex、Gemini 的 CLI 配置文件
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig 获取指定平台的 CLI 配置
 */
export function GetConfig(platform: string): $CancellablePromise<$models.CLIConfig | null> {
    return $Call.ByID(1263080270, platform).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLockedFields 获取指定平台的锁定字段列表
 */
export function GetLockedFields(platform: string): $CancellablePromise<string[]> {
    return $Call.ByID(1393452899, platform).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTemplate 获取指定平台的全局模板
 */
export function GetTemplate(platform: string): $CancellablePromise<$models.CLITemplate | null> {
    return $Call.ByID(2146148202, platform).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RestoreDefault 恢复默认配置
 */
export function RestoreDefault(platform: string): $CancellablePromise<void> {
    return $Call.ByID(2204458067, platform);
}

/**
 * SaveConfig 保存 CLI 配置
 */
export function SaveConfig(platform: string, editable: { [_: string]: any }): $CancellablePromise<void> {
    return $Call.ByID(3461150403, platform, editable);
}

/**
 * SetTemplate 设置指定平台的全局模板
 */
export function SetTemplate(platform: string, template: { [_: string]: any }, isGlobalDefault: boolean): $CancellablePromise<void> {
    return $Call.ByID(768927510, platform, template, isGlobalDefault);
}

// Private type creation functions
const $$createType0 = $models.CLIConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.CLITemplate.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
