// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetStatus(): $CancellablePromise<$models.ConfigImportStatus> {
    return $Call.ByID(2109164227).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportAll 从默认路径导入 cc-switch 配置
 */
export function ImportAll(): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(124174517).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportFromPath 从指定路径导入 cc-switch 配置
 */
export function ImportFromPath(path: string): $CancellablePromise<$models.ConfigImportResult> {
    return $Call.ByID(2519238097, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportMCPFromJSON 导入解析后的 MCP 服务器（用于多服务器批量导入）
 */
export function ImportMCPFromJSON(servers: $models.MCPServer[], conflictStrategy: string): $CancellablePromise<number> {
    return $Call.ByID(2891198368, servers, conflictStrategy);
}

/**
 * IsFirstRun 检查是否首次使用（用于显示导入提示）
 */
export function IsFirstRun(): $CancellablePromise<boolean> {
    return $Call.ByID(4249749624);
}

/**
 * MarkFirstRunDone 标记首次使用已完成（不再显示导入提示）
 */
export function MarkFirstRunDone(): $CancellablePromise<void> {
    return $Call.ByID(838327945);
}

/**
 * ParseMCPJSON 解析 JSON 字符串为 MCP 服务器列表
 * 支持三种格式：
 * 1. {"mcpServers": {"name": {...}}} - Claude Desktop 格式
 * 2. [{"name": "...", "command": "..."}] - 数组格式
 * 3. {"command": "...", "args": [...]} - 单服务器格式
 */
export function ParseMCPJSON(jsonStr: string): $CancellablePromise<$models.MCPParseResult | null> {
    return $Call.ByID(489842720, jsonStr).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3119656637);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2083779375);
}

// Private type creation functions
const $$createType0 = $models.ConfigImportStatus.createFrom;
const $$createType1 = $models.ConfigImportResult.createFrom;
const $$createType2 = $models.MCPParseResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
