// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Addr(): $CancellablePromise<string> {
    return $Call.ByID(285658449);
}

/**
 * GetAllLastUsedProviders 获取所有平台最后使用的供应商
 * @author sm
 */
export function GetAllLastUsedProviders(): $CancellablePromise<{ [_: string]: $models.LastUsedProvider | null }> {
    return $Call.ByID(1820257126).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLastUsedProvider 获取指定平台最后使用的供应商
 * @author sm
 */
export function GetLastUsedProvider(platform: string): $CancellablePromise<$models.LastUsedProvider | null> {
    return $Call.ByID(4045318450, platform).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1467206330);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3260822682);
}

// Private type creation functions
const $$createType0 = $models.LastUsedProvider.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
