// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RequestDetailService 请求详情服务（供前端调用）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearCache 清空缓存
 */
export function ClearCache(): $CancellablePromise<void> {
    return $Call.ByID(3977949689);
}

/**
 * GetAvailableIDs 获取当前缓存中所有可用的 sequence_id
 */
export function GetAvailableIDs(): $CancellablePromise<number[]> {
    return $Call.ByID(620313087).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCacheStats 获取缓存统计信息
 */
export function GetCacheStats(): $CancellablePromise<$models.CacheStats> {
    return $Call.ByID(3179050857).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDetail 根据序号获取请求详情
 */
export function GetDetail(sequenceID: number): $CancellablePromise<$models.RequestDetail | null> {
    return $Call.ByID(4109240113, sequenceID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetRecentDetails 获取最近的请求详情列表
 */
export function GetRecentDetails(limit: number): $CancellablePromise<($models.RequestDetail | null)[]> {
    return $Call.ByID(408261339, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRecordMode 获取当前记录模式
 */
export function GetRecordMode(): $CancellablePromise<string> {
    return $Call.ByID(2604268834);
}

/**
 * SetRecordMode 设置记录模式
 * mode: "off" | "fail_only" | "all"
 */
export function SetRecordMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(2240837270, mode);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.CacheStats.createFrom;
const $$createType2 = $models.RequestDetail.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
